name: flutter_master_app
description: Multi-tenant SaaS starter
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  dio: 5.9.1
  flutter_riverpod: 2.6.3

flutter:
  uses-material-design: true
  generate: true


dev_dependencies:
  flutter_test:
    sdk: flutter
